### ISSUE TITLE
pytorch_geometric version

### ISSUE THREAD

**Issue by dtjayaaa12345** [joeybose/Meta-Graph#1]
hi joey, 
   Could you please provide a requirements.txt for running this code? 
   It seems my pytorch_geometric version is not consistent with this project.
   Thanks so much!

**Comment by joeybose** [comment]
I used 1.2 or whatever the latest version is. I'll make a proper README in the coming month.

**Comment by dathath** [comment]
Can you please update the repo with the proper README?
