### ISSUE TITLE
Could you pls add the proper Readme?

### ISSUE THREAD

**Issue by ha-lins** [joeybose/Meta-Graph#2]
Hi @joeybose ,

Interesting work! I wonder if you have the plan to update the Readme and add more instructions? Thanks!

**Comment by joeybose** [comment]
Hey, I plan to update things hopefully in the next 1-2 weeks now that all the deadlines are out of the way.

**Comment by ha-lins** [comment]
Thanks a lot!

**Comment by joeybose** [comment]
Hey, I've updated the codebase and README slightly. As there are many combinations of possible runs you should look at the arg parser for a very specific setting. Alternatively, If there's a specific experiment you want to run I can update the README with it's description.

**Comment by ha-lins** [comment]
Thanks a lot! : )
